---
title: 异常处理
date: 2022-06-22 09:03:37

categories:
  - 后端
  - java
tags:
  - 
sitemap:
  exclude: false
  changefreq: monthly
---

## try catch

`try catch` 语句用于捕获可能出现的错误。如果不需要捕获特定类型的错误，那么使用`Exception e` 即可。 

```java
try {
    String s = processFile(“C:\\test.txt”);
    // ok:
} catch (SecurityException e) {
    // no read permission:
} catch (IOException e) {
    // io error:
} catch (Exception e) {
    // other error:
} finally{ // 总会被执行
    // end 
}
```

因为当被其中一个catch捕获后，后续的catch不会再继续执行，所以在catch时， **子类必须写在父类前面，否则子类的错误永远不会被捕获**，例如：

```java
try {
    String s = processFile(“C:\\test.txt”);
} catch (Exception e) {
} catch (IOException e) { // 永远不会被执行，因为 IOException 是 Exception 的子类
}
```

#### 捕获多种异常

```java
public static void main(String[] args) {
    try {
        ...
    } catch (IOException | NumberFormatException e) { // 两者没有继承关系
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```

## throws

一个方法可以通过 `throws` 关键词声明可能抛出的异常类型，例如：

```java
public byte[] getBytes(String charsetName) throws UnsupportedEncodingException { // 获取字符串的比特表示，如果字符串是由不支持的编码表示的，则获取失败
    ...
}
```

当执行 `getBytes` 方法时， **必须捕获** 方法声明的异常类型。调用者面临两种选择：
1.  用 `try catch` 捕获可能发生的错误
2.  如果调用者是函数方法，可以选择继续 `throws` 这个错误

```java
// 选择1
try{
    getBytes()
}catch(UnsupportedEncodingException e){

}
// 选择二
// 转换成GBK编码函数
public byte[] toGBK(String s) throws UnsupportedEncodingException{ // 继续丢给上层处理 
    return s.getBytes("GBK"); // 获取字符串按GBK编码解析成的比特流
}
```


## 打印错误日志

`e.printStackTrace()` 可以帮我们打印错误日志

```java
public byte[] toGBK(String s) {
    try {
        return s.getBytes("GBK");
    } catch (UnsupportedEncodingException e) {
        // 先记下来再说:
        e.printStackTrace();
    }
    return null;
}
```

## try()

`Try()` 即 *try-with-resources* 是 *Java7* 中的一个新的异常处理机制，它能够很容易的**关闭在 `try-catch` 语句中使用的资源**。

它主要是为了处理 `try-finally` 下的一种情况。下面是来自[https://blog.csdn.net/andyzhaojianhui/article/details/79876516]https://blog.csdn.net/andyzhaojianhui/article/details/79876516的一个例子：

```java
private static void printFile() throws IOException {
    InputStream input = null;
 
    try {
        input = <strong>new FileInputStream("file.txt")</strong>;
 
        int data = <strong>input.read()</strong>;
        while(data != -1){
            System.out.print((char) data);
            data = <strong>input.read()</strong>;
        }
    } finally {
        if(input != null){
            <strong>input.close()</strong>;
        }
    }
}
```

在这个例子中，开发者打开了一个文件 `file.txt` 并在 `finally` 中将其关闭。但这里有一种场景，在关闭文件`file.txt`时也有可能会抛出错误（例如文件被占用）。根据异常的调用栈，`finally` 是最后抛出的错误，它会覆盖 `try` 中抛出的错误。

如果我们想要获取 `try` 语句中抛出的错误，则需要使用 `try()` 写法。

```java
private static void printFileJava7() throws IOException {
 
    try(FileInputStream input = new FileInputStream("file.txt")) {
 
        int data = input.read();
        while(data != -1){
            System.out.print((char) data);
            data = input.read();
        }
    }
}
```
其有两个特性：

- 因为 `FileInputStream` 实现了java中的 `java.lang.AutoCloseable` 接口，其在 `try()` 内使用，则在 `try` 语句结束后会**自动调用自动关闭的接口方法**。
- 在自动调用 `java.lang.AutoCloseable` 接口中抛出的错误不会抑制 `try` 语句中爆出的错误。即我们抛出的是 `try{}` 语句中的错误而不是自动关闭时发生的错误。
